### ISSUE TITLE
Implement a second VM besides EVM that uses IOTA‘s UTXO model at its fullest potential.

### ISSUE THREAD

**Issue by kranebitt** [iotaledger/iota-sdk-evm#1]
## Description

Implementation of a native IOTA L2 Smart Contract Framework that is UTXO based.

## Motivation

It would allow to really use IOTAs full potential and to overcome the limitations of the account based model (EVM) known from Ethereum.

## Requirements

1. Chose a SC framework, ideally compatible with the Cardano/Ergo world (Plutus/Ergoscript) or another sound and technically advanced one.
2. Create a second EVM compatible with that framework.
3. Release it first on Shimmer and then on IOTA
4. Promote the benefits of having UTXO on L2

## Open questions (optional)

Which framework to pick,
since ressources are limited. 
Funding? IOTA or maybe project catalyst funding.

## Are you planning to do it yourself in a pull request?

No.

**Comment by Dr-Electron** [comment]
This should be an issue in [wasp](https://github.com/iotaledger/wasp) 🤔 Or a [TIP discussion](https://github.com/iotaledger/tips/discussions) I guess....
